### PR TITLE
Done with reverse_polish

### PR DESCRIPTION
**Pull request by Elvis020**
image

### CODE REVIEW

**Review by Aceix — CHANGES_REQUESTED** [review]
use correct file naming: `<name>-<desc>.py`

**Comment by Elvis020** [comment]
ano dey barb oo, i should use the same folder name or the problem is with my function name?

**Comment by Elvis020** [comment]
Oh ok, i barb, i forgot to add my name

**Comment by Elvis020** [comment]
ok, den merge it, let me change it and raise another PR for corrections, also shouldn't be the merged branches be deleted?
Else decline the PR and let me raise another one

**Comment by Elvis020** [comment]
done, I have renamed file should be good to merge

**Review by Aceix — APPROVED** [review]

**Pull request merged**
